---
title: "bkmr_attempt"
author: "Alana Ferris"
date: "2024-04-10"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(foreign)
library(dplyr)
library(mgcv)
library(splines)
```


```{r message=FALSE, warning=FALSE, echo = FALSE}
### Reading in Relevant NHANES 2017-2018 Data
#NOTE: phthalate and AGP data have special sample weights we need to account for in analysis
#weighting module: https://wwwn.cdc.gov/nchs/nhanes/tutorials/Weighting.aspx

# phthalates and plasticizers metabolites - urine 
# codebook, LODs: https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/PHTHTE_J.htm
phthte_urine =
  read.xport("data/PHTHTE_J.XPT") %>% 
  janitor::clean_names()

# urine creatinine levels 
# codebook: https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/ALB_CR_J.htm
creatinine_urine =
  read.xport("data/ALB_CR_J.XPT") %>% 
  janitor::clean_names()

# Alpha-1-Acid Glycoprotein - Serum
# codebook: https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/SSAGP_J.htm
agp_serum =
  read.xport("data/SSAGP_J.XPT") %>% 
  janitor::clean_names()

# Demographic variables and sample weights 
# codebook: https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DEMO_J.htm
demo =
  read.xport("data/DEMO_J.XPT") |> 
  janitor::clean_names()
```

```{r message=FALSE, warning=FALSE, echo = FALSE}
# Cleaning Variable Names of Phthalate Urine Data 

phthte_urine =
  phthte_urine %>% 
  rename(weights = wtsb2yr) %>%
  rename_with(~ gsub("^urx", "", .), starts_with("urx")) %>% 
  filter(!weights == "0") %>% 
  select(-mcoh, -mhnc, -mhp, -mnp)
```

```{r message=FALSE, warning=FALSE, echo = FALSE}
# Adjusting Phthalate Urine Data for Creatinine

# merging Phthalate urine data with urinary creatinine levels and then adjusting concentrations for creatinine
# dropping albumin from creatinine dataset
creatinine_urine =
  creatinine_urine %>% 
  select(seqn, urxucr, urducrlc) #dropping urxcrs bc i dont want creatinine expressed in those units
#7936 obs

#merging creatinine data with phthalate data
phthte_creatinine =
  merge(creatinine_urine, phthte_urine, by = "seqn") %>%
  select(!starts_with("urd")) %>% #dropped <LOD columns for ease of pivoting
  pivot_longer(cols = cnp:mzp,  
               names_to = "analyte_code",
               values_to = "reported_result") #pivoted longer so that i can map in the next step

#54169 obs 

#urinary [phth] in ng/mL
# urinary [creatinine] in mg/dL so need to get this to ng/mL

# Urinary creatinine concentrations, specific gravity, and osmolality are common methods for adjusting dilution. The most widely used method is creatinine adjustment that involves dividing the analyte concentration by the creatinine concentration. Analyte results are then reported as weight of analyte per gram of creatinine (micrograms analyte per gram creatinine).

# making a new column with creatinine-adjusted [phthalate]
phthte_creatinine =
  phthte_creatinine %>% 
  mutate(ng_per_ml_creatinine = urxucr*10000) %>% #here converting mg/dL to ng/mL--> 1mg/dL = 10,000ng/mL
  mutate(adj_conc = reported_result/ng_per_ml_creatinine)
```

```{r message=FALSE, warning=FALSE, echo = FALSE}
# Cleaning Variable Names of Demographic Data

# drop unneeded variables from dataset 
demo <- subset(demo, select = -c(sddsrvyr, ridstatr, ridexprg, dmdmartl, dmdeduc2, dmqmiliz, dmqadfc, dmdhrgnd, dmdhragz, dmdhredz, dmdhrmaz, dmdhsedz))

demo <- demo |> 
  rename(gender = riagendr, 
         age_yrs_screen = ridageyr, 
         age_mon_screen = ridagemn, 
         race_ethn1 = ridreth1,
         race_ethn3 = ridreth3, 
         time_period = ridexmon, 
         age_mon_screen = ridagemn,
         age_mon_exam = ridexagm, 
         birth_country = dmdborn4, 
         citizenship = dmdcitzn,
         years_us = dmdyrsus, 
         education = dmdeduc3, 
         lang_pers_quest = sialang, 
         proxy_pers_quest = siaproxy, 
         interpret_pers_quest = siaintrp, 
         lang_fam_interview = fialang, 
         proxy_fam_interview = fiaproxy, 
         interpret_fam_interview = fiaintrp,
         lang_capi = mialang, 
         proxy_capi = miaproxy, 
         interpret_capi = miaintrp, 
         lang_acasi = aialanga, 
         hh_size = dmdhhsiz, 
         fam_size = dmdfmsiz, 
         hh_young_children = dmdhhsza,
         hh_children = dmdhhszb, 
         hh_adults = dmdhhsze, 
         weight_2yr_intervew = wtint2yr,
         weight_2yr_mec = wtmec2yr, 
         variance_psu = sdmvpsu, 
         variance_stratum = sdmvstra, 
         income_hh_annual = indhhin2, 
         income_family_annual = indfmin2, 
         income_poverty_ratio = indfmpir)
```

```{r message=FALSE, warning=FALSE, echo = FALSE}
# Subsetting Demographic Data to Ages 3-16 

demo <- demo |> 
  filter(age_yrs_screen >= 3 & age_yrs_screen <= 16)

# filtering for only covariates we need
demo_new = demo |> 
  select(seqn, gender, age_yrs_screen, race_ethn3, income_family_annual)
```

```{r message=FALSE, warning=FALSE, echo = FALSE}
#Joining demographic, phthalate, and agp data

#making phthalate adjusted with creatinine dataset wide so can join with demo data
wide_phth_creat =
  phthte_creatinine %>%
  select(-reported_result, -ng_per_ml_creatinine) %>% 
  pivot_wider(names_from = "analyte_code",
              values_from = "adj_conc") %>% 
  filter(!rowSums(is.na(select(., cnp:mzp))) == ncol(select(., cnp:mzp))) #2851 to 2762
#noticed that participant #93739, 93771, has no data for any of the pththalate metabolites, even in phthte_urine dataset, so should drop them from further analysis?
# there are many participants with no values for any of them , even in phthte_urine dataset 
# went back to checkin_feb_20_deliverable to get rid of them there 


exp_outcome =
  inner_join(wide_phth_creat, agp_serum, by = "seqn") %>% 
  filter(!is.na(ssagp)) #662 participants that provided agp samples and have phthalate data for 
  
summary(exp_outcome)
(292/954)*100
##########

all_exp_outcome = inner_join(exp_outcome, demo_new, by = "seqn") |> 
  mutate(gender_female = if_else(gender == 1, 1, 0)) |>  #making a binary assignment of gender for multiple regression male = 0, female = 1
  mutate(eth_mex = case_when(race_ethn3 == 1 ~ 1, TRUE ~ 0),
         eth_hisp_oth = case_when(race_ethn3 == 2 ~ 1, TRUE ~ 0),
         eth_white = case_when(race_ethn3 == 3 ~ 1, TRUE ~ 0),
         eth_black = case_when(race_ethn3 == 4 ~ 1, TRUE ~ 0),
         eth_asian = case_when(race_ethn3 == 6 ~ 1, TRUE ~ 0),
         eth_nonhispanic_multirace = case_when(race_ethn3 == 7 ~ 1, TRUE ~ 0)) #%>% 
  #select(-ucr)

all_data =
  inner_join(demo, wide_phth_creat, by = "seqn") #915 people with demo and phthalate data


all_data_with_outcome <- all_data %>% 
  inner_join(agp_serum, all_data, by = "seqn")

sum(exp_outcome$seqn %in% all_data$seqn)

# All of the covariates, exposure, and outcome data
all_var <- all_data_with_outcome |> 
  mutate(gender_female = if_else(gender == 1, 1, 0)) |>  #making a binary assignment of gender for multiple regression male = 0, female = 1
  mutate(eth_mex = case_when(race_ethn3 == 1 ~ 1, TRUE ~ 0),
         eth_hisp_oth = case_when(race_ethn3 == 2 ~ 1, TRUE ~ 0),
         eth_white = case_when(race_ethn3 == 3 ~ 1, TRUE ~ 0),
         eth_black = case_when(race_ethn3 == 4 ~ 1, TRUE ~ 0),
         eth_asian = case_when(race_ethn3 == 6 ~ 1, TRUE ~ 0),
         eth_nonhispanic_multirace = case_when(race_ethn3 == 7 ~ 1, TRUE ~ 0)) 


```

# attempt 1: Research question
What is the overall effect of exposure to mixture of phthalate/phthalate alternatives on AGP levels?

```{r}
# 0b Load packages
# analysis 
library(bkmr)
# data management 
library(readr)
library(dplyr) 
library(ggplot2)
library(fastDummies) 
```

# ignore this 
```{r}
# set.seed(111)
# 
# #create a matrix of exposures
# exposures <- select(all_var, cnp:mzp)
# 
# exposures_matrix <- as.matrix(exposures)
# 
# #Put confounders in a matrix
# #first, merging all_data with exp_outcome (all data is such a misnomer lol)
# # dta =
# #   left_join(exp_outcome, all_data, by = "seqn")
# # 
# # confounders <- dta %>%
# #   dplyr::select(gender, age_yrs_screen, race_ethn1, race_ethn3) #removing income poverty ratio for now bc i think we can't have missing data for this
# # 
# # confounders <- as.matrix(confounders)
# # summary(confounders)
# 
# ## **somehow there are a lot of NAs in demographic info for this population??? idk, someone should verify this, bc of that i am not going to include confounders this time around bc u cannot have NAs in BKMR ** ## 
# 
# #Fit BKMR model
# # This will take a 1.25 hours to run. 
# 
# fitkm <- kmbayes(y = all_var$ssagp,   # outcome variable
#                  Z = exposures,       # dataframe of exposures
#                  X = NULL, # dataframe of confounders
#                  iter = 10000,    # number of iterations
#                  verbose = FALSE, # print interim progress of model?
#                  varsel = TRUE)   # 
# 
# #Save BMKR Model
# saveRDS(fitkm, file = "data/initial_bkmr_solution.RDS")
# 
# # Read in BKMR Model 
# fitkm <- readRDS("data/initial_bkmr_solution.RDS")
```
# attempt 2: Research question
What is the overall effect of exposure to mixture of phthalate/phthalate alternatives on AGP levels?

# Fit BKMR model
```{r}
set.seed(111)

#create a matrix of exposures
exposures <- select(all_exp_outcome, cnp:mzp)

exposures_matrix <- as.matrix(exposures)

#Put confounders in a matrix
#gender, age_yrs_screen, race_ethn1, race_ethn3, income_family_annual
confounders <- all_exp_outcome %>%
  dplyr::select(gender, age_yrs_screen, race_ethn3)

confounders <- as.matrix(confounders)
summary(confounders)

#Fit BKMR model
# This will take a ~8 minutes to run. 

adj_fitkm <- kmbayes(y = all_exp_outcome$ssagp,   # outcome variable
                 Z = exposures_matrix,       # dataframe of exposures
                 X = confounders, # dataframe of confounders
                 iter = 10000,    # number of iterations
                 verbose = FALSE, # print interim progress of model?
                 varsel = TRUE)   # 

#Save BMKR Model
saveRDS(adj_fitkm, file = "data/adj_bkmr_solution.RDS")

# Read in BKMR Model 
adj_fitkm <- readRDS("data/adj_bkmr_solution.RDS")
```

# Assess BKMR Convergence
```{r}
# betas are confounders 
TracePlot(fit = adj_fitkm, par = "beta") #looks converged

TracePlot(fit = adj_fitkm, par = "beta", comp = 1) #looks converged

TracePlot(fit = adj_fitkm, par = "beta", comp = 2) # looks converged 

# "sigsq.eps" and "r" are tuning parameters of the bayesian model 
# sigsq refers to the sigma of the kernel 
# and r refers to the parameter used to estimate the PIP 
TracePlot(fit = adj_fitkm, par = "sigsq.eps") #looks converged

TracePlot(fit = adj_fitkm, par = "r", comp = 1) 
TracePlot(fit = adj_fitkm, par = "r", comp = 2)
# im not sure if r seems converged...idk how to interpret this one 

```

# plot BKMR results...
```{r}
# Posterior inclusion probabilities 
# The PIP is the probability that the exposure is an important 
# part of the mixture

ExtractPIPs(adj_fitkm, z.names = c("cnp", "cop", "ecp", "ecpt", "hibp", "mbp", "mc1", "mep", "mhbp", "mhh", "mhht", "mib", "moh", "monp", "mzp"))

#they all basically have the same importance...mep seems to maybe have highest by slightest amount

# Set plot theme 
plotTheme <- theme(axis.title = element_text(size = 19), 
                   axis.text = element_text(size = 17),
                   strip.text = element_text(size = 19), 
                   title = element_text(size = 22), 
                   legend.text = element_text(size = 17), 
                   legend.title = element_text(size = 19)) 

# 4b Plot Univariate exposure-response

# 4b.i Estimate exposure-response for each exposure 
# When the other exposures are at their median value 
# In the presence of interaction, 
# there is not a single exposure-response curve
# the association between the exposure and outcome depends on the other exposures
# For example, if there were interaction by sex 
# then there would be one effect estimate among males 
# and one among females
# note: we can ignore the warning about tibble

adj_pred.resp.univar <- PredictorResponseUnivar(fit = adj_fitkm, 
                                            q.fixed = 0.5, # set other exposures to 50th percentile
                                            z.names = c("cnp", "cop", "ecp", "ecpt", "hibp", "mbp", "mc1", "mep", "mhbp", "mhh", "mhht", "mib", "moh", "monp", "mzp")) 

#Create Plot 

mixture_interaction <- ggplot(adj_pred.resp.univar, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + 
  geom_smooth(stat = "identity") + 
  facet_wrap(~ variable, scales = "free_x") +
  xlab("Phthalate Concentrations") + 
  ylab("Change in Expected AGP") + 
  plotTheme + theme(
  # Change overall plot size
  plot.title = element_text(size = 10),  # Title size
  axis.title = element_text(size = 8),   # Axis title size
  axis.text = element_text(size = 4)     # Axis text size
)

ggsave("output/mixture_interaction.pdf", plot = mixture_interaction)


# every univariate association null lol and no interaction 

# Plot exposure-response of total mixture
# Estimate exposure-response for each quantile 

#this takes a couple minutes to run 
adj_responses.overall <- OverallRiskSummaries(fit = adj_fitkm,     # model 
                                      y = all_exp_outcome$ssagp,   # outcome 
                                      Z = exposures_matrix,       # exposures
                                      X = confounders, # matrix of confounders 
                                      qs = seq(0.25, 0.75, by = 0.05), # vector of quantiles
                                      q.fixed = 0.5, 
                                      method = "exact") # estimation method

#Table of Responses
adj_responses.overall 

# 4d.iii Plot

mixture_overall <- ggplot(adj_responses.overall, aes(quantile, est, ymin = est - 1.96*sd, 
                              ymax = est + 1.96*sd)) + 
  geom_pointrange() + 
  ylab("Change in Expected AGP") + 
  plotTheme +
  labs(x = "Quantile", y = "Change in Expected AGP", title = "Overall Mixture Effect")

ggsave("output/mixture_overall.pdf", plot = mixture_overall)

# saw absolutely null effect of mixtures of phthalates on AGP levels....
```


