---
title: "Multiple Imputations"
author: "Christine Lucille Kuryla"
date: "2024-04-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load data

# Load and Clean Data

```{r message=FALSE, warning=FALSE, echo = FALSE}

library(tidyverse)
library(broom)
library(dplyr)
library(tidyverse)
library(foreign)
library(dplyr)
library(mgcv)

### Reading in Relevant NHANES 2017-2018 Data
#NOTE: phthalate and AGP data have special sample weights we need to account for in analysis
#weighting module: https://wwwn.cdc.gov/nchs/nhanes/tutorials/Weighting.aspx

# phthalates and plasticizers metabolites - urine 
# codebook, LODs: https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/PHTHTE_J.htm
phthte_urine =
  read.xport("data/PHTHTE_J.XPT") %>% 
  janitor::clean_names()

# urine creatinine levels 
# codebook: https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/ALB_CR_J.htm
creatinine_urine =
  read.xport("data/ALB_CR_J.XPT") %>% 
  janitor::clean_names()

# Alpha-1-Acid Glycoprotein - Serum
# codebook: https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/SSAGP_J.htm
agp_serum =
  read.xport("data/SSAGP_J.XPT") %>% 
  janitor::clean_names()

# Demographic variables and sample weights 
# codebook: https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DEMO_J.htm
demo =
  read.xport("data/DEMO_J.XPT") |> 
  janitor::clean_names()
```

```{r message=FALSE, warning=FALSE, echo = FALSE}
# Cleaning Variable Names of Phthalate Urine Data 

phthte_urine =
  phthte_urine %>% 
  rename(weights = wtsb2yr) %>%
  rename_with(~ gsub("^urx", "", .), starts_with("urx")) %>% 
  filter(!weights == "0") %>% 
  select(-mcoh, -mhnc, -mhp, -mnp)
```

```{r message=FALSE, warning=FALSE, echo = FALSE}
# Adjusting Phthalate Urine Data for Creatinine

# merging Phthalate urine data with urinary creatinine levels and then adjusting concentrations for creatinine
# dropping albumin from creatinine dataset
creatinine_urine =
  creatinine_urine %>% 
  select(seqn, urxucr, urducrlc) #dropping urxcrs bc i dont want creatinine expressed in those units
#7936 obs

#merging creatinine data with phthalate data
phthte_creatinine =
  merge(creatinine_urine, phthte_urine, by = "seqn") 

# Changing the <LODs to NA


# Get the metabolite columns and their corresponding lc columns using regex
#cols <- colnames(phthte_creatinine)
# pattern <- "^urd(.*)lc$"
# lc_columns <- cols[grepl(pattern, cols)]
# metabolites <- sub(pattern, "\\1", lc_columns)

lc_columns <- c("urducrlc", "urdcnplc", "urdcoplc", "urdecplc", "urdepclc", "urdhiblc", "urdmbplc", "urdmc1lc", "urdmcolc", "urdmeplc", "urdmhblc", "urdmhhlc", "urdmhtlc", "urdmchlc", "urdmhplc", "urdmiblc", "urdmnplc", "urdmohlc", "urdmonlc", "urdmzplc")
metabolites <- c("ucr", "cnp", "cop", "ecp", "ecpt", "hibp", "mbp", "mc1", "mcoh", "mep", "mhbp", "mhh", "mhht", "mhnc", "mhp", "mib", "mnp", "moh", "monp", "mzp")

# Function to apply NA where lc column indicates below detection limit
apply_detection_limit <- function(df, met, lc) {
  df[[met]][df[[lc]] == 1] <- NA
  df
}

# Loop through the metabolites and their corresponding lc columns to apply the function
for (i in seq_along(metabolites)) {
  phthte_creatinine <- apply_detection_limit(phthte_creatinine, metabolites[i], lc_columns[i])
}


# Remove the lc columns from the dataframe
phthte_creatinine <- phthte_creatinine %>% select(-matches("lc$"))




#%>%
#  select(!starts_with("urd")) %>% #dropped <LOD columns for ease of pivoting
  
  
phthte_creatinine = phthte_creatinine %>% 
  pivot_longer(cols = cnp:mzp,  
               names_to = "analyte_code",
               values_to = "reported_result") #pivoted longer so that i can map in the next step

#54169 obs 

#urinary [phth] in ng/mL
# urinary [creatinine] in mg/dL so need to get this to ng/mL

# Urinary creatinine concentrations, specific gravity, and osmolality are common methods for adjusting dilution. The most widely used method is creatinine adjustment that involves dividing the analyte concentration by the creatinine concentration. Analyte results are then reported as weight of analyte per gram of creatinine (micrograms analyte per gram creatinine).

# making a new column with creatinine-adjusted [phthalate]
phthte_creatinine =
  phthte_creatinine %>% 
  mutate(ng_per_ml_creatinine = urxucr*10000) %>% #here converting mg/dL to ng/mL--> 1mg/dL = 10,000ng/mL
  mutate(adj_conc = reported_result/ng_per_ml_creatinine)
```



```{r message=FALSE, warning=FALSE, echo = FALSE}
# Cleaning Variable Names of Demographic Data

# drop unneeded variables from dataset 
demo <- subset(demo, select = -c(sddsrvyr, ridstatr, ridexprg, dmdmartl, dmdeduc2, dmqmiliz, dmqadfc, dmdhrgnd, dmdhragz, dmdhredz, dmdhrmaz, dmdhsedz))

demo <- demo |> 
  rename(gender = riagendr, 
         age_yrs_screen = ridageyr, 
         age_mon_screen = ridagemn, 
         race_ethn1 = ridreth1,
         race_ethn3 = ridreth3, 
         time_period = ridexmon, 
         age_mon_screen = ridagemn,
         age_mon_exam = ridexagm, 
         birth_country = dmdborn4, 
         citizenship = dmdcitzn,
         years_us = dmdyrsus, 
         education = dmdeduc3, 
         lang_pers_quest = sialang, 
         proxy_pers_quest = siaproxy, 
         interpret_pers_quest = siaintrp, 
         lang_fam_interview = fialang, 
         proxy_fam_interview = fiaproxy, 
         interpret_fam_interview = fiaintrp,
         lang_capi = mialang, 
         proxy_capi = miaproxy, 
         interpret_capi = miaintrp, 
         lang_acasi = aialanga, 
         hh_size = dmdhhsiz, 
         fam_size = dmdfmsiz, 
         hh_young_children = dmdhhsza,
         hh_children = dmdhhszb, 
         hh_adults = dmdhhsze, 
         weight_2yr_intervew = wtint2yr,
         weight_2yr_mec = wtmec2yr, 
         variance_psu = sdmvpsu, 
         variance_stratum = sdmvstra, 
         income_hh_annual = indhhin2, 
         income_family_annual = indfmin2, 
         income_poverty_ratio = indfmpir)
```

```{r message=FALSE, warning=FALSE, echo = FALSE}
# Subsetting Demographic Data to Ages 3-16 

demo <- demo |> 
  filter(age_yrs_screen >= 3 & age_yrs_screen <= 16)
```

```{r message=FALSE, warning=FALSE, echo = FALSE}
#Joining demographic, phthalate, and agp data

#making phthalate adjusted with creatinine dataset wide so can join with demo data
wide_phth_creat =
  phthte_creatinine %>%
  select(-reported_result, -ng_per_ml_creatinine) %>% 
  pivot_wider(names_from = "analyte_code",
              values_from = "adj_conc") %>% 
  filter(!rowSums(is.na(select(., cnp:mzp))) == ncol(select(., cnp:mzp))) #2851 to 2762
#noticed that participant #93739, 93771, has no data for any of the pththalate metabolites, even in phthte_urine dataset, so should drop them from further analysis?
# there are many participants with no values for any of them , even in phthte_urine dataset 
# went back to checkin_feb_20_deliverable to get rid of them there 


all_data =
  inner_join(demo, wide_phth_creat, by = "seqn") #915 people with demo and phthalate data


all_data_with_outcome <- all_data %>% 
  inner_join(agp_serum, all_data, by = "seqn")



#exp_outcome <- inner_join(agp_serum, wide_phth_creat, by = "seqn")

exp_outcome <- inner_join(agp_serum, wide_phth_creat, by = "seqn") %>% 
  filter(!is.na(ssagp))

# exp_outcome =
#   inner_join(wide_phth_creat, agp_serum, by = "seqn") %>% 
#   filter(!is.na(ssagp)) #662 participants that provided agp samples and have phthalate data for 
  
summary(exp_outcome)
(292/954)*100

```

# Dataset

```{r}

demo_new = demo |> 
  select(seqn, gender, age_yrs_screen, race_ethn3, income_family_annual)

all_exp_outcome = inner_join(exp_outcome, demo_new, by = "seqn") |> 
  mutate(gender_female = if_else(gender == 1, 1, 0)) |>  #making a binary assignment of gender for multiple regression male = 0, female = 1
  mutate(eth_mex = case_when(race_ethn3 == 1 ~ 1, TRUE ~ 0),
         eth_hisp_oth = case_when(race_ethn3 == 2 ~ 1, TRUE ~ 0),
         eth_white = case_when(race_ethn3 == 3 ~ 1, TRUE ~ 0),
         eth_black = case_when(race_ethn3 == 4 ~ 1, TRUE ~ 0),
         eth_asian = case_when(race_ethn3 == 6 ~ 1, TRUE ~ 0),
         eth_nonhispanic_multirace = case_when(race_ethn3 == 7 ~ 1, TRUE ~ 0)) %>% 
  select(-ucr)

sum(exp_outcome$seqn %in% all_data$seqn)

# All of the covariates, exposure, and outcome data
all_var <- all_data_with_outcome |> 
  mutate(gender_female = if_else(gender == 1, 1, 0)) |>  #making a binary assignment of gender for multiple regression male = 0, female = 1
  mutate(eth_mex = case_when(race_ethn3 == 1 ~ 1, TRUE ~ 0),
         eth_hisp_oth = case_when(race_ethn3 == 2 ~ 1, TRUE ~ 0),
         eth_white = case_when(race_ethn3 == 3 ~ 1, TRUE ~ 0),
         eth_black = case_when(race_ethn3 == 4 ~ 1, TRUE ~ 0),
         eth_asian = case_when(race_ethn3 == 6 ~ 1, TRUE ~ 0),
         eth_nonhispanic_multirace = case_when(race_ethn3 == 7 ~ 1, TRUE ~ 0)) 

all_var1 <- all_var %>% 
  rename("MCNP" = "cnp",
         "MCOP" = "cop",
         "MECPP" = "ecp",
         "MECPTP" = "ecpt", 
         "MHiBP" = "hibp",
         "MBP" = "mbp",
         "MCPP" = "mc1",
         "MEP" = "mep",
         "MnBP" = "mhbp",
         "MEHHP" = "mhh" ,
         "MEHHTP" = "mhht",
         "MiBP" = "mib" ,
         "MEOHP" = "moh" ,
         "MONP" = "monp",
         "MBzP" = "mzp"
         )

all_var <- all_var1

```


# Multiple Imputations

```{r}
## A: Only Confounder Data Missing
# A1: Load MAR Data - Confounders Only
# A2: Visualize Missingness
# A3: Impute Missing Data 
# A4: Fit Model on Imputed Data
# A5: Pool Models
# A6: Compare to Model from Original Data

library(readr)
library(dplyr)
library(mice)
library(VIM)

# 0c Declare directories

# 0d Turn off scientific notation

options(scipen=999)

####*******************************************

##*************************************##
#### A: Only Confounder Data Missing ####
##*************************************##

####********************
##### A1: Load Data ####
####********************

# 1a Load data 

#df.Conf.miss <- read_csv(paste0(ProjectFolder, "county_bmi_miss_confounders.csv"))

#df.Conf.miss <- all_var # this won't run
df.Conf.miss <- all_exp_outcome %>% 
  select(-c("seqn", "wtssgp2y", "urxucr", "weights")) %>% 
  select(-c("mcoh", "mhnc", "mhp", "mnp")) %>% 
  rename("MCNP" = "cnp",
         "MCOP" = "cop",
         "MECPP" = "ecp",
         "MECPTP" = "ecpt", 
         "MHiBP" = "hibp",
         "MBP" = "mbp",
         "MCPP" = "mc1",
         "MEP" = "mep",
         "MnBP" = "mhbp",
         "MEHHP" = "mhh" ,
         "MEHHTP" = "mhht",
         "MiBP" = "mib" ,
         "MEOHP" = "moh" ,
         "MONP" = "monp",
         "MBzP" = "mzp"
         )

# 1b Review data

head(df.Conf.miss)

####*******************************
#### A2: Visualize Missingness ####
####*******************************

# 2a Count number of missing for each variable

summary(df.Conf.miss)

sum(is.na(df.Conf.miss$gender))
sum(is.na(df.Conf.miss$age_yrs_screen))
sum(is.na(df.Conf.miss$race_ethn1))
sum(is.na(df.Conf.miss$race_ethn3))
sum(is.na(df.Conf.miss$income_family_annual))
sum(is.na(df.Conf.miss$cnp))
sum(is.na(df.Conf.miss$cop))
sum(is.na(df.Conf.miss$ecp))
sum(is.na(df.Conf.miss$ecpt))
sum(is.na(df.Conf.miss$hibp))
sum(is.na(df.Conf.miss$mbp))
sum(is.na(df.Conf.miss$mc1))
sum(is.na(df.Conf.miss$mcoh))
sum(is.na(df.Conf.miss$mep))
sum(is.na(df.Conf.miss$mhbp))
sum(is.na(df.Conf.miss$mhh))
sum(is.na(df.Conf.miss$mhht))
sum(is.na(df.Conf.miss$mhnc))
sum(is.na(df.Conf.miss$mhp))
sum(is.na(df.Conf.miss$mib))
sum(is.na(df.Conf.miss$mnp))
sum(is.na(df.Conf.miss$moh))
sum(is.na(df.Conf.miss$monp))
sum(is.na(df.Conf.miss$mzp))


# 2b Review pattern of missingness

# We will isolate just the variables with missing data so it is easier to see them 
df.miss.vars <- df.Conf.miss %>% select("MCNP":"MBzP")

# 2b.i Visualize with VIM package 

aggr_plot <- aggr(df.miss.vars, 
                  col=c('navyblue','red'), 
                  numbers=TRUE,
                  sortVars=TRUE, 
                  labels=names(df.miss.vars), 
                  cex.axis=.7, 
                  gap=3, 
                  ylab=c("Histogram of missing data","Pattern"))


# 2b.ii Visualize with mice package

# this doesn't work because there is only one column of interest with missing data

# png(paste0("MissingPatterns.png"))
# md.pattern(df.miss.vars)
# dev.off()

# 2c Visual missingness of two variables 

# df.miss.vars2 <- df.Conf.miss %>% dplyr::select(MedHInc, LTHS)
# dev.off()
# marginplot(df.miss.vars2, xlab = "Median Household Income", ylab = "Percent Less than HS")
```


```{r impute, eval = FALSE}
####*****************************
#### A3: Impute Missing Data ####
####*****************************


df.Conf.miss_original <- df.Conf.miss

# df.Conf.miss_selected <- df.Conf.miss %>%
#   select(ssagp, age_yrs_screen, cnp:eth_nonhispanic_multirace)
# 
# df.Conf.miss <- df.Conf.miss_selected

# 3a Create imputed datasets

MImput.df.Conf <- mice(df.Conf.miss,     # dataset
              m = 5,        # number of imputed datasets to create
              maxit = 50,   # number of iterations to create prediction models 
              meth = 'pmm', # method for imputation- depends on the class of missing variables
                            # pmm usually performs best for continuous variables
              seed = 500)   # our seed

# education and year_us are linearly dependent so need to remove one of them
# all(df.Conf.miss$education == df.Conf.miss$years_us)
# 
# library(caret)
# nzv <- nearZeroVar(df.Conf.miss)
# colnames(df.Conf.miss)[nzv]
# df.Conf.miss <- df.Conf.miss[, -nzv]
# 
# # Check for high correlation
# cor_matrix <- cor(df.Conf.miss, use = "complete.obs")  # using complete cases for correlation
# high_cor <- findCorrelation(cor_matrix, cutoff = 0.9)  # identify highly correlated variables
# df.Conf.miss <- df.Conf.miss[, -high_cor]              # remove highly correlated variables

# Re-run mice
MImput.df.Conf <- mice(df.Conf.miss, m = 5, maxit = 50, meth = 'pmm', seed = 500)


MImput.df.Conf <- mice(df.Conf.miss,     # dataset
              m = 5,        # number of imputed datasets to create
              maxit = 50,   # number of iterations to create prediction models 
              meth = 'pmm', # method for imputation- depends on the class of missing variables
                            # pmm usually performs best for continuous variables
              seed = 500)   # our seed

# We get a warning because there 1 one county missing the ClimateRegion
# And therefore ClimateRegion cannot be included in the imputation equations

# 3b Review imputed datasets

ls(MImput.df.Conf)
summary(MImput.df.Conf)

# 3c Review imputed values for a single variable 

MImput.df.Conf$imp$mhp


# 3d Compare density plot of imputed data versus original data 

densityplot(MImput.df.Conf)



####***********************************
#### A4: Fit Model on Imputed Data ####
####***********************************


# 4A Fit models

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MCNP + gender + age_yrs_screen + race_ethn3 + income_family_annual))

##** Class Question **##
# How many regression models do I run in this step? 
##*****************************************************************##

####*********************
#### A5: Pool Models ####
####*********************

# 5a Model summary 

pool(mod.MImput.Conf)


# ubar = average within-imputation variance (sample variance)
# b = between-imputation variance

# riv = relative increase in variance due to missingness
# lambda = proportion of variance due to missingness 
# fmi = fraction of missing information

# Let us look at just the metabolite
pool(mod.MImput.Conf)[2,]

# we can directly compute the standard error of Beta 
# from the two sources of variance
# Var = se^2
# se = sqrt(ubar + ((m+ 1)/m)* b))

#sqrt(0.0007955 + ((5 + 1)/5) * 0.000000335992)

# 5b Model summary II 
# summary() will compute the standard error for us

mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

####*********************************************
#### A6: Compare to Model from Original Data ####
####*********************************************

# 6a Readin original, complete data 

#df.complete <- read_csv(paste0(ProjectFolder, "county_bmi_pm_confounders_10.csv"))

# 6b Create model with original data

mod.NoMiss <- summary(lm(ssagp ~ MCNP + gender + age_yrs_screen + race_ethn3 + income_family_annual,  data = df.Conf.miss))


# 6c Compare coefficient estimates

mod.NoMiss$coefficients[2:6,1]
mod.MImput.Conf.PooledCoeff[2:6,2]

# 6c Compare standard errors 

mod.NoMiss$coefficients[2:6,2]
mod.MImput.Conf.PooledCoeff[2:6,3]


```


```{r}

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MnBP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MCPP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MONP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MCNP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MHiBP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MiBP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MBzP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MBP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MEP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MEHHTP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MCOP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MECPP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MECPP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MECPTP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MEHHP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]

mod.MImput.Conf <- with(MImput.df.Conf, lm(ssagp ~ MEOHP + gender + age_yrs_screen + race_ethn3 + income_family_annual))
pool(mod.MImput.Conf)
pool(mod.MImput.Conf)[2,]
mod.MImput.Conf.PooledCoeff <- summary(pool(mod.MImput.Conf))
mod.MImput.Conf.PooledCoeff[2,]


#### A6: Compare to Model from Original Data ####

mod.NoMiss <- summary(lm(ssagp ~ MCNP + gender + age_yrs_screen + race_ethn3 + income_family_annual,  data = df.Conf.miss))
# 6c Compare coefficient estimates
mod.NoMiss$coefficients[2:6,1]
mod.MImput.Conf.PooledCoeff[2:6,2]
# 6c Compare standard errors 
mod.NoMiss$coefficients[2:6,2]
mod.MImput.Conf.PooledCoeff[2:6,3]




```




# Practice Work - Seeing if MI Dataset can be compared to Nonlinear Work
```{r}

#first fit linear model 

old_nocovari= lm(ssagp ~ cnp + cop + ecp + ecpt + hibp + mbp + mc1 + mep + mhbp + mhh + mhht + mib + moh + monp + mzp, data = exp_outcome)

summary(old_nocovari)

lin_covari_model = lm(ssagp ~ cnp + cop + ecp + ecpt + hibp + mbp + mc1 + mep + mhbp + mhh + mhht + mib + moh + monp + mzp + gender_female + age_yrs_screen + income_family_annual + race_ethn3, data = all_exp_outcome)

summary(lin_covari_model)

#fit complete model with penalized splines 

total_model <- gam(ssagp  ~ s(cnp) + s(cop) + s(ecp) + s(ecpt) + s(hibp) + s(mbp) + s(mc1) + s(mep) + s(mhbp) + s(mhh) + s(mhht) + s(mib) + s(moh) + s(monp) + s(mzp) + gender_female + age_yrs_screen + income_family_annual + race_ethn3, data = all_exp_outcome)

summary(total_model)

#edf not equal to 1 for ecpt, mcoh, mep, mhh, mhht, mhnc, mib, mzp
#going to fit GAM models with penalized splines for those 8 metabolites



```

